# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

inhibit_all_warnings!

target "TrackMyTime" do
pod "SVProgressHUD"
pod "TTCounterLabel"
pod "MMDrawerController"
pod "DSLCalendarView"
pod "XYPieChart"
pod 'TSMessages'
end

target "TrackMyTimeTests" do

end

